### PR TITLE
[WIP] Docs and more

### PR DESCRIPTION
**Pull request by wcwitt**
More improvements (mostly docs) in advance of the paper release.

### CODE REVIEW

**Comment by cortner** [comment]
Thank for the cleanup. 

My only concern here is removing all the links from the sidebar. This is a bit of a matter of taste I think. Not everybody wants to click through many pages to get to the information they want. 

Can we get some additional feedback from some users?

**Comment by wcwitt** [comment]
I had hoped to add the tutorials in a dropdown within the sidebar but wasn't sure how to do it at the time ... but I've managed it just now. I think (?) the only other page I removed from the sidebar (besides the outdated) was the Pkg info.

**Comment by cortner** [comment]
merge?

**Comment by wcwitt** [comment]
Just made a few tweaks to better incorporate the Molly tutorial. Merging.

**Pull request merged**
