### PR TITLE
WIP: ACEfit integration

### PR DESCRIPTION
**Pull request by cortner**
CC @wcwitt, @gelzinyte  - I'm going to get this started and put together a first 1-2 examples that use both and then we can discuss here how to move everything over.

### CODE REVIEW

**Comment by cortner** [comment]
tests fail, this needs the `ace1pack` branch of `ACEfit.jl` to work.

**Comment by cortner** [comment]
note I can't convert the TiAl example to a md or html page yet because somehow Literate doesn't find the artifacts file. Does anybody have any ideas? (@gelzinyte ??)

**Comment by cortner** [comment]
@wcwitt - I think I've done everything I wanted for now, and I can leave this alone for a while and let you synchronize with your own work.

**Comment by cortner** [comment]
@wcwitt can you remind me what we are waiting for to merge this? Maybe we just need to tag a first version of ACEfit as soon as you are comfortable and then bring ACEfit as an alternative into ACE1pack, but not yet support it fully in the Dict interface?

**Comment by wcwitt** [comment]
> and then bring ACEfit as an alternative into ACE1pack, but not yet support it fully in the Dict interface

@cortner, does this mean you want to support IPFitting and ACE1pack simultaneously? This PR removes IPFitting - I was thinking we'd make an IPFitting branch before merging this, and then maintain that branch in parallel until IPFitting is retired completely. But open to suggestions!

Overall I was planning to finish everything here (https://github.com/ACEsuit/ACEfit.jl/projects/1), then tag ACEfit, then merge this afterwards.

**Comment by cortner** [comment]
I’m ok with that too. Sounds like we should tag a 0.1.x with IPFitting and 0.2.x with ACEfit?

**Comment by cortner** [comment]
@wcwitt  - can you merge the latest `main` into this branch, and then let me know when it is ready to tag as 0.2.0?

**Comment by wcwitt** [comment]
@cortner, done. Would you please tag as 0.2.0? Preferably after tagging ACEfit 0.0.2.

**Comment by cortner** [comment]
so just to confirm, we merge this into main and tag it as 0.2, then continue the IPFitting version in the 0.1 branch, correct?

**Comment by wcwitt** [comment]
That sounds good to me. And doing it that way will force me to fix any transition speedbumps quickly.

**Pull request merged**
