### PR TITLE
add Molly tutorial and ACEmd

### PR DESCRIPTION
**Pull request by tjjarvinen**
This will implement Molly tutorial for #147

### CODE REVIEW

**Comment by cortner** [comment]
Thank you - your message says "will" but this looks essentially ready? 

My only question is whether `ACEmd` should be a dependency for `ACE1pack` given it is only exported but then not used. How heavy is that dependency? Does it pull in also Molly? Other heavy packages?

**Comment by tjjarvinen** [comment]
yes this is essentially done.

For the export, I was a considering also not exporting. But considering JuLIP retirement, ACEmd is coming in at some point. ACEmd does not pull more than CellListMap, Unitful and AtomsBase in addition to what we have, Molly is an extension.

The other option would be to have ACEmd as a weakdep, so that we can control version in Project.toml, as the tutorial does make some expectations on ACEmd version.

I am not completely sure for the export and now that I think about it, the weakdep route might be a better at this point.

**Comment by cortner** [comment]
Ok thank you, that makes sense. - leave for now and wait for feedback from @wcwitt - I think his preference might be to minimise extensions.

**Comment by cortner** [comment]
You say "Essentially done", what is left?

**Comment by tjjarvinen** [comment]
> You say "Essentially done", what is left?

Only requested changes

**Comment by cortner** [comment]
@wcwitt - unless you have an objection I will merge?

**Comment by wcwitt** [comment]
No objections, and thank you. Longer term, it might be useful to clarify the relationship between `ACEpotential` in ACEmd and `ACE1Model`. For example, I like that ACEmd has a `load_ace_model` routine ... ACE1pack really needs something like that to encapsulate the `read_dict` stuff. But an ACE1pack user who utilizes that routine currently may not get what they expect

**Comment by cortner** [comment]
Thanks, Chuck, I added those points to the TODO list. I'll merge this for now. There will be work to fix ACEmd to correctly interact with some of those changes, but we can do this in future PRs.

**Comment by cortner** [comment]
thank you, @tjjarvinen

**Pull request merged**
