### PR TITLE
Fix docs build

### PR DESCRIPTION
**Pull request by cortner**

### CODE REVIEW

**Comment by wcwitt** [comment]
Thanks, I was just wondering about this

**Comment by cortner** [comment]
Some exports changed somewhere. I'm on it. Will try to fix today.

**Comment by wcwitt** [comment]
Oh it looked to me like your commit fixed it already.

Also I was hoping we’d be able to test the versioned docs here based on the
tag you made. But it looks like we’ll have to merge before we’ll see the
versions

**Comment by cortner** [comment]
indeed it did, I thought I saw a failure, but it must have been a different branch, then I can merge now.

**Pull request merged**
