### PR TITLE
ace_fit.jl control numpy threads 

### LINKED ISSUE #71: set number of blas threads more widely
https://github.com/ACEsuit/ACE1pack.jl/blob/a51295085a9fe45ea588d8cfb81a9fcb3f009e1a/scripts/ace_fit.jl#L48

Would it be helpful, or just annoyingly complicated, if `ace_fit.jl` set all the known BLAS env vars for multithreading, i.e. `MKL_NUM_THREADS`, `OPENBLAS_NUM_THREADS`, maybe also plain `OMP_NUM_THREADS`, since some of the optimizers (namely the ones in `scikit-learn`) use those instead of the julia-internal value?

closed by #72

### PR DESCRIPTION
**Pull request by bernstei**
ace_fit.jl set all possible env vars controlling numpy numbers of threads when --num-blas-threads is passed

closes #71

### CODE REVIEW

**Comment by bernstei** [comment]
Could we actually just call `threadpool_info` mentioned here https://stackoverflow.com/questions/30791550/limit-number-of-threads-in-numpy?

**Comment by wcwitt** [comment]
Have you managed to verify whether setting the environment variables this way works? I assume yes, but if they need to be set before `import numpy` (perhaps only in older python?), I'm not exactly sure what that means for us.

**Comment by bernstei** [comment]
I haven't.  Note that `threadpool_limits` is definitely supposed to work after import.  Let me do some tests.  If `threadpool_limits` works with MKL, do we consider that sufficient to just go with that?

**Comment by wcwitt** [comment]
The `threadpoolctl` option looks nice too - maybe better because we could print the `threadpool_info()` just before calling the solver to verify. We'd need to figure out how to do `with threadpool_limits(limits=1, user_api='blas'):` in Julia, or something equivalent.

Edit: I wrote this before seeing your last comment. But this sounds good to me:

> If threadpool_limits works with MKL, do we consider that sufficient to just go with that?

**Comment by bernstei** [comment]
I guess it's a python context manager, so it's not at all obvious how to call it from julia, which I gather is using `pyimport` to call particular python functions (specifically the sklearn optimizer constructors, which then create julia objects with `fit()` methods).

**Comment by bernstei** [comment]
I just noticed that the version of `ace_fit.jl` that my julia is actually using and this repo version are very different.  Do you know why that is?

**Comment by wcwitt** [comment]
> I just noticed that the version of ace_fit.jl that my julia is actually using and this repo version are very different. Do you know why that is?

Yours should match the 0.0.x branch. But I'll make sure these changes go both places.

**Comment by wcwitt** [comment]
For now, give me a day or two to do these?

https://github.com/ACEsuit/IPFitting.jl/issues/39
https://github.com/ACEsuit/ACEfit.jl/issues/35

That will help us know when we've solved the problem

**Comment by bernstei** [comment]
Definitely - if you can get `threadpoolctl` to work, that'd be much cleaner.

**Comment by wcwitt** [comment]
I think this is working now. Here's the version for IPFitting: https://github.com/ACEsuit/ACE1pack.jl/pull/74.

Edit: looks like the CI is failing here, but for an unrelated reason. The tests in the more stable #74 passed.

**Comment by bernstei** [comment]
Great, thanks @wcwitt

**Comment by bernstei** [comment]
Do you want me to test it? If so, can you tell me how to switch to the relevant version in my julia configuration?

**Pull request merged**
