### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by WillBaldwin0**
@cortner @gelzinyte, I've made some small changes to a lot of files, fixing some typos and making sure everything reads and links together correctly. Also added the python usage. 

I noticed that for those only using command line, we'll need to add a script to ACE1pack which just calls the export function to convert a `.json` to a `.yace`. I'm happy to write that, or we could make `ace_fit` automatically export to `.yace`.

### CODE REVIEW

**Comment by wcwitt** [comment]
Thanks a lot Will.

> or we could make ace_fit automatically export to .yace

That sounds good to me.

**Comment by cortner** [comment]
so it will produce two files, a json and a yace? I'm defintely ok with that.

**Comment by WillBaldwin0** [comment]
I will merge this if no one else has any comments?

**Comment by WillBaldwin0** [comment]
Also, since I've modified the ace_fit script to do the automatic exporting, do we need to take a version?

**Comment by gelzinyte** [comment]
Looks good, thanks a lot! I think exporting `yace` automatically is more convenient.

**Pull request merged**
