### PR TITLE
Domain argument for `site_descriptors`

### PR DESCRIPTION
**Pull request by cortner**
Related to [this issue](https://github.com/ACEsuit/ACE1.jl/issues/80)

@siasolt -- do you mind trying this out.

### CODE REVIEW

**Comment by cortner** [comment]
If it's not clear how to try this: 
- clone the `ACEpotentials.jl` repo
- checkout the `descriptors` branch
- In your project folder
    - activate the project
    - go to package manager `]`
    - `dev folder_to_ACEpotentials`
- restart all Julia instances in which you want to test this.

**Comment by siasolt** [comment]
This worked!

**Comment by cortner** [comment]
@wcwitt  -- this is a tiny and trivial change to the current implementation. Can you take a brief glance and confirm whether or not you are happy for me to merge this?

**Comment by wcwitt** [comment]
Fine with me, thanks. Hopefully my tweak will fix the CI (related: https://github.com/ACEsuit/ACEpotentials.jl/pull/183#issuecomment-1783319842).

**Comment by cortner** [comment]
registered as 0.6.4 

@siasolt  -- if you can now `free ACEpotentials` then put a version bound of 0.6.4 in your project and it should then update your manifest and packages automatically.

**Pull request merged**
