### PR TITLE
Adapt to new strategy for recomputing weights

### PR DESCRIPTION
**Pull request by wcwitt**
Two main things:

* update the test for weight recomputation and add it to runtests (it wasn't actually in the test suite before).
* begin removing some of the temporary hacks in `src/model.jl` related to weight recomputation.

@cortner are you okay with these? Ultimately, I would be happy to refactor the model assembly routine (removing `weights_only`) but wanted to check with you first.

### CODE REVIEW

**Comment by wcwitt** [comment]
I've cancelled the tests because they will fail until we have tagged a new ACEfit version.

**Comment by cortner** [comment]
I thought I did a fair bit of that yesterday. Can we please check the remaining PRs and compare? I'm sorry I didn't realise there was another branch...

**Comment by cortner** [comment]
ACEfit is already tagged and released.

**Comment by cortner** [comment]
hm - on taking a closer look, maybe a simple merge of main into this branch will do?

**Comment by cortner** [comment]
this looks all good. I'll merge the PR as soon as tests are finished. I'll then merge the tutorials branch as well and we can start a new tutorials branch in the fork.

**Comment by wcwitt** [comment]
Great thanks - I did try to avoid duplicating your changes

**Pull request merged**
