### PR TITLE
Starting a test suite

### PR DESCRIPTION
**Pull request by cortner**
Starting a test suite, ideally bring it to parity with ACEpotentials paper last year. So far tests don't run because of memory problems. To be investigated.

### CODE REVIEW

**Comment by cortner** [comment]
The memory problems are fixed by #246 . The first zuo example script now runs and produces ok results. 

I'm now trying to add an ASP example on one of the Zuo datasets, but the solver returns only the last result and not the path. Probably a bug (might have been introduced by me).  @tinatorabi  --  would you mind looking into this?  If I figure something out myself, I'll let you know immediately.

**Comment by cortner** [comment]
```
Energy Error
┌────┬─────────┬──────────┬──────┬──────┐
│    │ ACE(sm) │ ACE(lge) │  GAP │  MTP │
├────┼─────────┼──────────┼──────┼──────┤
│ Ni │   0.409 │    0.334 │ 0.42 │ 0.48 │
│ Cu │   0.291 │     0.22 │ 0.46 │ 0.41 │
│ Li │   0.233 │    0.166 │ 0.49 │ 0.49 │
│ Mo │   2.386 │     2.88 │ 2.24 │ 2.83 │
│ Si │   3.522 │    2.305 │ 2.91 │ 2.21 │
│ Ge │   2.669 │    2.192 │ 2.06 │ 1.79 │
└────┴─────────┴──────────┴──────┴──────┘
Force Error
┌────┬─────────┬──────────┬──────┬──────┐
│    │ ACE(sm) │ ACE(lge) │  GAP │  MTP │
├────┼─────────┼──────────┼──────┼──────┤
│ Ni │   0.018 │    0.015 │ 0.02 │ 0.01 │
│ Cu │   0.007 │    0.005 │ 0.01 │ 0.01 │
│ Li │   0.006 │    0.005 │ 0.01 │ 0.01 │
│ Mo │   0.122 │    0.096 │ 0.09 │ 0.09 │
│ Si │   0.086 │    0.065 │ 0.07 │ 0.06 │
│ Ge │   0.063 │    0.051 │ 0.05 │ 0.05 │
└────┴─────────┴──────────┴──────┴──────┘
```
Looking ok so far. I think this makes me comfortable to merge this PR and fix the ASP test asap.

**Comment by cortner** [comment]
Screenshot 2024-09-11 at 13 41 22

For comparison this is the result from the paper. Essentially the same.

**Comment by tinatorabi** [comment]
@cortner I tried this and once you have the results via `results= ACEfit.solve(solver, AW, YW, AWv, YWv)`, `results["C"]` gives you the best model parameters on the validation set based on the chosen selection mode and to get the parameters for the full path you'd have to do something like `[p[:solution] for p in results["path"]]`. Do we need this returned as well?

**Comment by cortner** [comment]
I missed that there was a kwarg to get the path. I've now removed that and ALWAYS specify this.

**Pull request merged**
