### PR TITLE
bugfix.

### LINKED ISSUE #193: Tests Failing
Test tests are currently failing - in a seemingly begnin way. Need to go through them and adjust/fix as appropriate.

### PR DESCRIPTION
**Pull request by wcwitt**
Aims to resolve #193. Hopefully the CI will pass.

### CODE REVIEW

**Comment by wcwitt** [comment]
The first problem I noticed is fixed, but there is another issue related to `atomsbase`.

**Comment by wcwitt** [comment]
@tjjarvinen would you mind taking a look here?

**Comment by tjjarvinen** [comment]
It seems to be a tolerance issue. The new fitting method, does not work as well as the old one and that tripped one of the (very loose) test tolerance checks. It should work now.

**Comment by cortner** [comment]
Im a bit nervous about loosening the tolerance. What changed?

**Comment by tjjarvinen** [comment]
The change to fitting method does not seem to converge as well as the previous setting.

We could look more on why it does not converge as well or loosen the tolerance. Latter is faster, but we could miss also something.

Also it looks like that ultrafast ACE has some test failing also...

**Comment by cortner** [comment]
re uf_ace, probably just a matter of switching from max-error to mae or even better fixing a seed. Anyhow this is experimental.

**Comment by cortner** [comment]
what do we do about this now?

**Comment by cortner** [comment]
so it was just a random fail. I'll fix that at some point ...

**Comment by wcwitt** [comment]
Sorry for the slow reply - if it fails again we can look more closely.

**Pull request merged**
