### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by wcwitt**
A few minor things mixed together (sorry). The main goal was to begin converting everything (e.g., tests) to `acemodel`, but in the meantime I fixed a few of the warnings that were causing the CI to fail. Mainly: deleting the duplicate `at_dimer` and updating `linear_assemble` to `assemble`. The latter is breaking, unfortunately.

### CODE REVIEW

**Comment by cortner** [comment]
I assume this needs to wait for https://github.com/ACEsuit/ACEfit.jl/issues/63 ??

**Comment by cortner** [comment]
Unfortunately removing duplicates is also in #144  -- but should be easy to fix in a merge.

**Comment by cortner** [comment]
Actually this looks ready now. the update to 0.1.2 just happens anyhow and I can confirm it gets rid of the boring warnings. I will merge and tag a minor version.
```
(ACE1pack) pkg> status
Project ACE1pack v0.4.1
Status `~/gits/ACE1pack.jl/Project.toml`
  [e3f9bc04] ACE1 v0.11.13
  [5cc4c08c] ACE1x v0.1.6
  [ad31a8ef] ACEfit v0.1.2
  [352459e4] ExtXYZ v0.1.12
  [a98d9a8b] Interpolations v0.14.7
  [945c410c] JuLIP v0.14.2
  [bac558e1] OrderedCollections v1.6.2
  [08abe8d2] PrettyTables v2.2.7
  [189a3867] Reexport v1.2.2
  [90137ffa] StaticArrays v1.6.2
  [ddb6d928] YAML v0.4.9
  [37e2e46d] LinearAlgebra
```

**Comment by cortner** [comment]
done, registered as version = v"0.5.0"

**Comment by wcwitt** [comment]
Thank you - the CI is now passing on Julia nightly as a result. It failed for a different reason (the docs Project.toml needed a new version bound), but I hope I've just fixed that.

**Pull request merged**
