### PR TITLE
Update documentation for AtomsBase

### PR DESCRIPTION
**Pull request by tjjarvinen**
AtomsBase documentation is a bit out of date. This will update it.

### CODE REVIEW

**Comment by cortner** [comment]
I think as we switch over to full AtomsBase integration we may choose to enforce units. I'm generally against it, but here it seems actually sensible. To be discussed elsewhere. 

But should this be merged into v0.6.x instead of main?

**Comment by tjjarvinen** [comment]
It should be in both.

The issue with units is that ExtXYZ can not save units. So, there is no reliable way to load them from a file. We would need to think how to deal with this too.

**Comment by cortner** [comment]
> The issue with units is that ExtXYZ can not save units. So, there is no reliable way to load them from a file. We would need to think how to deal with this too.

But the user who is loading the data would need to know what the units are. We could enforce that the user tells ACEpotentials what units to use. We could also use eV, A as defaults. I'm don't have an opinion yet. It will emerge over the next few weeks/months.

**Comment by cortner** [comment]
> It should be in both.

ok for me. How do you handle this? merge first into v0.6.x and then merge that into main? Or merge into main and then backport?

**Comment by tjjarvinen** [comment]
I posted anothen PR to v0.6.x branch #199 . That should make it easy.

**Comment by cortner** [comment]
can I merge both?

**Comment by tjjarvinen** [comment]
yes

**Pull request merged**
