### PR TITLE
Tweaks following a full pass through the documentation

### PR DESCRIPTION
**Pull request by wcwitt**
Overall, everything in the `dev` docs is pretty clean. A few small things:

* The weights should be squared here, right?
image

* There is one TODO in the smoothness prior tutorial
image

### CODE REVIEW

**Comment by cortner** [comment]
> The weights should be squared here, right?

yes. Thanks for spotting this.

**Comment by wcwitt** [comment]
Just pushed a fix for the loss function - let's see how it renders.

**Comment by wcwitt** [comment]
The latest, from https://acesuit.github.io/ACEpotentials.jl/previews/PR243/literate_tutorials/basic_julia_workflow/

image

**Comment by cortner** [comment]
This looks like I should merge, yes?

**Comment by wcwitt** [comment]
>There is one TODO in the smoothness prior tutorial

This is the only lingering item, but not essential to fix it now. Fine to merge if you like.

**Comment by cortner** [comment]
I'll merge this and let's file an issue to integrate smoothness priors into runfits as well as update the tutorials.

**Pull request merged**
