### PR TITLE
clean up dependencies.

### PR DESCRIPTION
**Pull request by wcwitt**
Addresses #143. I've gone through and removed everything not explicitly used in `src/`. That doesn't mean everything with `using` is _actually_ used, but I didn't take the time to dig that deeply.

The caveat is that many of these dependencies are required for `scripts/ACE1packMPI.jl`, but that is now a bit out of date. We can re-add them as appropriate.

Okay @cortner?

### CODE REVIEW

**Comment by cortner** [comment]
How about creating an MPI extension?

Similar to what I'm doing with the plotting extension.

**Comment by wcwitt** [comment]
Yeah maybe - I will consider that when I find time to revive the MPI properly. I decided to remove it completely for now.

Do you know why the CI is failing on Julia nightly? Maybe they've gotten more strict about some of these warnings?

**Comment by cortner** [comment]
I don't. I can try to look into it. Cannot promise when.

**Comment by cortner** [comment]
```
ERROR: LoadError: Method overwriting is not permitted during Module precompile.
```
Easy fix, that would fit well into #144 

I am guessing that to optimize precompilation they are now *forcing* packages to not overwrite anything. Would also help to curb type piracy. But I'm just speculating here.

**Pull request merged**
