### PR TITLE
Update ACE1pack for PythonCall

### PR DESCRIPTION
**Pull request by wcwitt**
Addresses #132. @tjjarvinen, here is what I've managed so far, but not working yet and I'm a little stuck. Want to take over?

### CODE REVIEW

**Comment by tjjarvinen** [comment]
It seems that tests files are loading `PyCall` still, which results as a failure - `test/test_silicon.jl` line 4 has it.

You need to do:

- Remove `PythonCall` from `project.toml`, but keep it in `test/Project.toml` - extensions mean that we don't need have `PythonCall` as a dependency
- Make sure non of the test files loads `PyCall` - change them to `PythonCall`

**Comment by wcwitt** [comment]
> It seems that tests files are loading PyCall still, which results as a failure - test/test_silicon.jl line 4 has it.

Not sure what you mean - check the changes in this PR.

> Remove PythonCall from project.toml, but keep it in test/Project.toml - extensions mean that we don't need have PythonCall as a dependency

Thanks - I've just done this.

**Comment by wcwitt** [comment]
Hm, the relevant tests are still segfaulting for me locally, although I think everything you suggested is done. Let's see what happens in the CI.

**Comment by wcwitt** [comment]
From the CI, and similar to what I see locally:

```
Transaction finished
free(): invalid pointer

[3204] signal (6.-6): Aborted
in expression starting at /home/runner/work/ACE1pack.jl/ACE1pack.jl/test/test_silicon.jl:4
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
raise at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f7ff86546f5)
unknown function (ip: 0x7f7ff866bd7b)
unknown function (ip: 0x7f7ff866dac3)
free at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
Py_DECREF at /usr/local/src/conda/python-3.11.4/Include/object.h:538 [inlined]
Py_XDECREF at /usr/local/src/conda/python-3.11.4/Include/object.h:602 [inlined]
_PyImport_LoadDynamicModuleWithSpec at /usr/local/src/conda/python-3.11.4/Python/importdl.c:246 [inlined]
_imp_create_dynamic_impl at /usr/local/src/conda/python-3.11.4/Python/import.c:2385 [inlined]
_imp_create_dynamic at /usr/local/src/conda/python-3.11.4/Python/clinic/import.c.h:446
cfunction_vectorcall_FASTCALL at /usr/local/src/conda/python-3.11.4/Objects/methodobject.c:427
```

**Comment by tjjarvinen** [comment]
ACEfit is still using v0.1.0? - should be v0.1.1 now.

**Comment by wcwitt** [comment]
Ah yes! Thanks - testing now. Forgot we'd pinned it at 0.1.0.

**Comment by wcwitt** [comment]
Tests pass locally, but fail in CI for Julia 1.8. That's not a surprise because of the J1.9 extension. I'll remove that part of the CI and try again.

**Comment by tjjarvinen** [comment]
CI needs to have v1.9, v1 and nightly.

**Comment by wcwitt** [comment]
The CI is passing - merging.

**Comment by cortner** [comment]
NB - this is already in 0.4.1

**Pull request merged**
