### PR TITLE
Fix rSH for ACEModel

### PR DESCRIPTION
**Pull request by CheukHinHoJerry**
This PR aims at fixing a small bug for using rSH.

### CODE REVIEW

**Comment by cortner** [comment]
I only see SH fix, but not the alternative intialization. Should we restrict the PR to the SH fix?

**Comment by CheukHinHoJerry** [comment]
Sure - let's do the rSH fix first.

**Comment by cortner** [comment]
Could we think of a simple test that checks explicitly that the correct Y basis was selected?

**Comment by CheukHinHoJerry** [comment]
How about picking `norm(Rs)` goes to `0`?

**Comment by CheukHinHoJerry** [comment]
- checking relative scaling for random r
- Setting parameters to 1 and 0 and look at the many body basis on `Rs` with `length(Rs)=1`?

**Comment by cortner** [comment]
Produce two bases and compare their behaviour in that limit? That sound good. Would you mind adding this?

**Comment by cortner** [comment]
You don't even have to do r to 0. just check the relative scaling for random r.

**Comment by CheukHinHoJerry** [comment]
I was looking for the `BB_spec` but couldn't find it elsewhere. My memory is that this is something that we should get from `_rpi_A2B_matrix`?

**Review by cortner — APPROVED** [review]

**Comment by CheukHinHoJerry** [comment]
Ah okay - over complicate things on my end. Thank you for fixing this.

**Comment by cortner** [comment]
@CheukHinHoJerry -- please confirm that my change to the spher vs solid test is ok. What you had was much more than I had intended and just got a bit too complicated for my taste. If you think there is something crucial missing from my simplified test let me know and we can bring yours back. 

If you are ok with this, then I'll merge.

**Comment by CheukHinHoJerry** [comment]
Looks good. Just to add I feel a bit uncomfortable working without BBspec now. That requires `(nn,ll)` from generating the `A2B` map. Shall we add that feature?

**Pull request merged**
