### PR TITLE
WIP: Save and Recover Project Information

### PR DESCRIPTION
**Pull request by cortner**
moving PR #247 to this repo to collaborate on it.

### CODE REVIEW

**Comment by cortner** [comment]
@CheukHinHoJerry  --  ready to continue on this. I was in a rush didn't manage to fully resolve the conflicts on `save_potential` - please take a look.

**Comment by CheukHinHoJerry** [comment]
No problem. Thanks for moving this.

**Comment by CheukHinHoJerry** [comment]
I will add test for recovering the manifest and project later too. Are those changes in the `Project.toml` intended?

**Comment by cortner** [comment]
> Are those changes in the Project.toml intended?

What changes? Removing EmpiricalPotentials and UFACE - yes, that was intended (for now). UFACE will be deleted permanently but EP I'll probably bring back over the weekend.

**Comment by CheukHinHoJerry** [comment]
This PR is ready for review.

**Comment by cortner** [comment]
thank you, Jerry!

**Pull request merged**
