### PR TITLE
updated argparse to work behind the scenes

### PR DESCRIPTION
**Pull request by gelzinyte**
Fix for #43. @cortner please merge if this looks ok and update the versions. Seems to work in a fresh environment for me.

### CODE REVIEW

**Comment by cortner** [comment]
looks good, but maybe can be simplified. It's late so I'm tempted to just merge, but I think the fact we reexport everything means you don't even need to do the `using ArgParse`? Have you tried this?

**Comment by gelzinyte** [comment]
Let me quickly try that

**Comment by cortner** [comment]
Do you want to very quickly hop onto Zoom?

**Comment by cortner** [comment]
@WillBaldwin0 -- we can merge and tag this PR now or wait until your workshop is over. Let us know.

**Comment by WillBaldwin0** [comment]
So will this also need pyjulip to be updated because pyjulip current does using ACE1 etc?

**Comment by cortner** [comment]
thanks for flagging this. Let's not merge then and figure out how to handle this. 

CC @casv2

**Comment by cortner** [comment]
my suggestion is that pyjulip could just go through a list of packages, check which are available, and import those. And if something doesn't work, throw an error message saying "most likely one of the required packages are not installed" ... or something along those lines?

**Comment by gelzinyte** [comment]
If I understand it correctly, this merge and a bump in version (which would also fix a bug) is waiting for pyjulip to be updated?

**Comment by casv2** [comment]
Just merge this we can make pyjulip work with however this is decided to work.

We'll have to look for the packages and raise an error if it's not there? Actually, pyjulip looks for ACE1 and JuLIP, but those are still around in ACE1pack right?

**Comment by gelzinyte** [comment]
Yes, ACE1pack re-exports ACE1, IPFitting and JuLIP. So now `using ACE1pack` is sufficient if you wanted to use any of the ACE1, JuLIP, etc functions. e.g. 

```
using ACE1pack 
db = LsqDB(...)
```
is enough and you don't have to `using IPFitting`. (in fact, that will raise an error, because formally IPFitting wasn't `added`. 

I guess pyjulip has to work with either a) only ACE1pack installed and b) ACE1, JuLIP, IPfitting, but not ACE1pack installed. 

If pyjulip is being updated v soon I can update the docs and merge this if @WillBaldwin0 and @cortner are happy?

The docs update: change one-liner to only install ACE1pack. Anything else?

**Comment by casv2** [comment]
If you're changing the docs to just install ACE1pack shouldn't pyjulip also just go through ACE1pack and go from there? 

Rename to pyACE1pack?

**Comment by gelzinyte** [comment]
once this is merged, @cortner could you also bump the version? (to 0.0.4)

**Comment by cortner** [comment]
done

**Pull request merged**
